name: 'Python Example App with CICD pipeline'

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  run-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
          cache: 'pip' # caching pip dependencies
      
      - run: pip install -r requirements.txt

      - name: GitHub Action for pylint
        uses: cclauss/GitHub-Action-for-pylint@0.7.0

      