name: 'Python Example App with CICD pipeline'

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  run-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
          cache: 'pip' # caching pip dependencies
      
      - run: |
          pip install -r requirements.txt
          pip install pylint

      - name: Analysing the code with pylint
        run: |
          pylint $(git ls-files '*.py')

      - name: Python security check 
        uses: Joel-hanson/bandit-report-artifacts@V1

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          tags: pythondemoapp:latest

      - uses: akhileshns/heroku-deploy@v3.12.14
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "pythondemoapp"
          heroku_email: "patrick.c.pierson@gmail.com"
          usedocker: true
          docker_heroku_process_type: web
          docker_build_args: |
            FLASK_ENV
        env:
          FLASK_ENV: app